bgg_analytics:
  target: dev
  outputs:
    dev:
      type: athena
      database: AwsDataCatalog
      schema: analytics
      region_name: ap-southeast-2
      s3_staging_dir: s3://boardgames-sommelier-athena-results-dev-021406833830
      s3_data_dir: s3://boardgames-sommelier-gold-dev-021406833830/analytics/
      work_group: boardgames_sommelier-bgg-workgroup
      threads: 4
      
    prod:
      type: athena
      database: AwsDataCatalog
      schema: analytics_prod
      region_name: ap-southeast-2
      s3_staging_dir: s3://boardgames-sommelier-athena-results-dev-021406833830
      s3_data_dir: s3://boardgames-sommelier-gold-dev-021406833830/analytics_prod/
      work_group: boardgames_sommelier-bgg-workgroup
      threads: 4
