version: 2

sources:
  - name: raw
    database: AwsDataCatalog
    schema: boardgames_sommelier_bgg_database
    tables:
      - name: dim_game
      - name: br_game_category
      - name: br_game_mechanic
      - name: br_game_theme
      - name: br_game_publisher
      - name: br_game_artist
      - name: fct_user_rating

models:
  - name: stg_games
    description: "Staging models or Boardgames Sommelier cleaned data."
    columns:
      - name: game_id
        description: "Unique identifier for each board game."
        tests:
          - unique
          - not_null
      - name: average_rating
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 10
  
  - name: dim_game_features
    description: "Feature-engineered dimension table for ML modeling."
    columns:
      - name: game_id
        description: "Unique identifier for each feature."
        tests:
          - unique
          - not_null